
WIN = 'WIN'
LOSE = 'LOSE'
COL = 15
ROW = 8
GOLD_QUANTITY = 8
SWORDS_QUANTITY = 10
WUMPUS_QUANTITY = 8
HOLES_QUANTITY = 8
GOLD = "G"
WUMPUS = "W"
HOLES = "O"
PLAYER = "J"
SIGNAL_WUMPUS = "+"
SIGNAL_HOLE = "~"
PLAYER = "J"
ALL_ELEMENTS = "GWOJ+~J"
ITEMS_DICTIONARY = {"O": "~", "W": "+"}

SCORE_GAME = {"move": -10, "gold_wumpus": 1000, "lost_shoot": -50}
